language: node_js
node_js: node
cache:
  directories:
    - node_modules
script:
    - npm run build
env:
  - CI=true

before_deploy:
  - npm install netlify-cli -g
  - npm run build

deploy:
  provider: script
  script: netlify deploy NETLIFY_SITE_ID $NETLIFY_SITE_ID NETLIFY_AUTH_TOKEN $NETLIFY_ACCESS_TOKEN
  skip_cleanup: true
  on:
    branch: master
