language: node_js
node_js: node
cache:
  directories:
    - node_modules
script:
    - npm run build
env:
  - CI=true

before_deploy:
  - npm install netlify-cli -g
  - npm run build

deploy:
  provider: script
  script: netlify deploy --site-id $NETLIFY_SITE_ID --access-token $NETLIFY_ACCESS_TOKEN --publish-directory ./build
  skip_cleanup: true
  on:
    branch: master
