language: node_js
node_js: node
cache:
  directories:
    - node_modules
script:
    - npm run build
env:
  - CI=true
  - NETLIFY_SITE_ID=9b9ccd31-14d8-458c-8821-fabd06fe28a4

before_deploy:
  - npm install netlify-cli -g
  - npm run build

deploy:
  provider: script
  script: netlify deploy --prod
  skip_cleanup: true
  on:
    branch: master
